version: '3.7'
services:
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
  postgres:
    image: postgres:11.5
    environment:
      POSTGRES_DB: tabung-sg-dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hunter2
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
volumes:
  pgdata:
