default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: tabung_sg_dev
  username: postgres
  password: hunter2
  host: localhost
  port: 5432
test:
  <<: *default
  database: tabung_sg_test
  username: postgres
  password: hunter2
  host: localhost
  port: 5432
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
